### PR TITLE
Reard rate sum

### PR DESCRIPTION
**Pull request by Abhishekkochar**
This should resolve the issue with #29. I have changed the reward per second to reward per day. This will give a readable figure to validators.

### CODE REVIEW

**Review by gophereth — APPROVED** [review]

**Comment by gophereth** [comment]
Is this converting all the numbers to bigNum or only partial ?

**Comment by Abhishekkochar** [comment]
This converts all the numbers where arithmetic operations are being performed. For example, eth price isn't a big number unless it's included in any math operations.

**Comment by gophereth** [comment]
> This converts all the numbers where arithmetic operations are being performed. For example, eth price isn't a big number unless it's included in any math operations.

Okay it means it's ready for merge? Did you test the code on your local?

**Comment by Abhishekkochar** [comment]
Yes, it's been tested thoroughly multiple times.

**Pull request merged**
